### ISSUE TITLE
JSON schema - Is definitions keyword supported?

### ISSUE THREAD

**Issue by omkarnix** [openapi-contrib/json-schema-to-openapi-schema#25]
Hi, I m facing exactly same issue as described in https://github.com/wework/json-schema-to-openapi-schema/issues/29

Can someone please share an update? @philsturgeon

**Comment by philsturgeon** [comment]
These issues are just “does something work?” so I don’t really understand the question. 

What are you trying to do.

What is the expected outcome.

What is the actual outcome? Errors, unexpected behaviour, etc.

**Comment by jonluca** [comment]
I see what the problem is, the `json-schema-walker` won't walk definitions that aren't referenced by a `$ref`. This should probably be supported though.

If a schema had a definitions property (which is valid in JSONSchema), and only some of those entries were referenced, only the referenced ones were converted, leaving the schema in a broken invalid state.

https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/30 This PR adds a new property (which is true by default, but can be disabled) to convert these definitions as well - convertUnreferencedDefinitions

**Comment by philsturgeon** [comment]
Awesome, thanks again @jonluca. If you find a moment to throw some docs up for that new property that'd help folks find it. You've been doing great on these PRs, I really appreciate it!

**Comment by jonluca** [comment]
Cool, will do it in a bit. No problem :)

I think the other issues on this repo can be closed out as well. They should all be cleared/done

**Comment by philsturgeon** [comment]
@jonluca thank you, closed them all but this one. https://github.com/openapi-contrib/json-schema-to-openapi-schema/issues/32
